---
title: "Data analysis"
output: html_notebook
---
 
```{r}
library(haven)
library(forcats)
```

```{r}
f1 <- factor(x = rep(1:3,5),
             levels = c(1,2,3),
             labels = c("Yes","No","N/A"))
f1
```

```{r}
summary(f1)
```

```{r}
levels(f1)
```

```{r}
f2 <- factor(x = c(-1,0,1,9),
             levels = c(-1,0,1,9),
             labels = c("Yes","No","N/A","Null"))
f2
```

```{r}
as.numeric(f2)
```

```{r}
as.character(f2)
```

```{r}
f3 <- factor(x = rep(1:3,5),
             levels = c(1,2,3),
             labels = c("Basic","Medium","High"),
             ordered = TRUE)
f3
```

```{r}
table(f3)
```
 in order to change order of levels we can use function relevel
 
```{r}
f1
relevel(f1, ref = "No")
```

We will create factors with package haven

```{r}
x1 <- labelled(x = rep(1:3,5),
               labels = c("Yes" = 1,
                          "No" = 2,
                          "N/A" = 3))
```


```{r}
x1
```

```{r}
f4 <- factor(x = rep(c(1,2,3), c(10,5,2)),
             levels = c(1,2,3),
             labels = c("Opt1","Opt2","Opt3"))
f4
```


```{r}
fct_lump(f4, n = 1, other_level = "Rest")
```

```{r}

```
